# Generated by Django 3.2.7 on 2021-10-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lpage', '0002_auto_20210920_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
